// <auto-generated />
using System;
using BundleTree.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BundleTree.Migrations
{
    [DbContext(typeof(BundleContext))]
    [Migration("20240908145238_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BundleTree.Models.Bundle", b =>
                {
                    b.Property<int>("BundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BundleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredUnits")
                        .HasColumnType("INTEGER");

                    b.HasKey("BundleId");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("BundleTree.Models.BundlePart", b =>
                {
                    b.Property<int>("BundlePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BundleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredUnits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubBundleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("BundlePartId");

                    b.HasIndex("BundleId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SubBundleId");

                    b.ToTable("BundleParts");
                });

            modelBuilder.Entity("BundleTree.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BundleTree.Models.BundlePart", b =>
                {
                    b.HasOne("BundleTree.Models.Bundle", "Bundle")
                        .WithMany("BundleParts")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BundleTree.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BundleTree.Models.Bundle", "SubBundle")
                        .WithMany()
                        .HasForeignKey("SubBundleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bundle");

                    b.Navigation("Product");

                    b.Navigation("SubBundle");
                });

            modelBuilder.Entity("BundleTree.Models.Bundle", b =>
                {
                    b.Navigation("BundleParts");
                });
#pragma warning restore 612, 618
        }
    }
}
